<a href="https://colab.research.google.com/github/mossytreesandferns/DataCampHomework/blob/master/PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Mount my drive- run the code, go to the link, accept.
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
#Change working directory to make it easier to access the files
import os
os.chdir("/content/gdrive/My Drive/Colab Notebooks/")
os.getcwd()

'/content/gdrive/My Drive/Colab Notebooks'

# Basics

In [0]:
True + False

1

# Lists

In [0]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],["bedroom", bed],["bathroom", bath]]
print(house)
print(type(house))
print(house[2])

[['hallway', 11.25], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>
['bathroom', 9.5]


In [0]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])
print(areas[-5])

eat_sleep_area = areas[3] + areas[7]
print(eat_sleep_area)
print()
downstairs=areas[0:6]
upstairs=areas[6:]
upstairs2=areas[-4:]
print(downstairs, upstairs, upstairs2)

11.25
9.5
20.0
28.75

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] ['bedroom', 10.75, 'bathroom', 9.5] ['bedroom', 10.75, 'bathroom', 9.5]


In [0]:
areas2 = [downstairs, upstairs]
areas2[-1][2]

'bathroom'

In [0]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
areas[4]="chill zone"
areas[-1]=10.5
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

In [0]:
areas= areas + ["poolhouse", 24.5] + ["garage", 15.0]
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'poolhouse',
 24.5,
 'garage',
 15.0,
 'poolhouse',
 24.5,
 'garage',
 15.0]

In [0]:
#del(areas[-4:-2])
areas

['hallway',
 'foo',
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5,
 'garage',
 15.0]

In [0]:
# To copy lists
#not this:
areas_copy = areas
areas_copy[1]="foo"
areas, areas_copy

(['hallway',
  'foo',
  'kitchen',
  18.0,
  'chill zone',
  20.0,
  'bedroom',
  10.75,
  'bathroom',
  10.5,
  'garage',
  15.0],
 ['hallway',
  'foo',
  'kitchen',
  18.0,
  'chill zone',
  20.0,
  'bedroom',
  10.75,
  'bathroom',
  10.5,
  'garage',
  15.0])

In [0]:
# do this
areas_copy1 = areas[:]
areas_copy2= list(areas)
areas_copy1[3]="coin"
areas_copy2[4]="ocean"
areas, areas_copy1, areas_copy2

(['hallway',
  'foo',
  'kitchen',
  18.0,
  'chill zone',
  20.0,
  'bedroom',
  10.75,
  'bathroom',
  10.5,
  'garage',
  15.0],
 ['hallway',
  'foo',
  'kitchen',
  'coin',
  'chill zone',
  20.0,
  'bedroom',
  10.75,
  'bathroom',
  10.5,
  'garage',
  15.0],
 ['hallway',
  'foo',
  'kitchen',
  18.0,
  'ocean',
  20.0,
  'bedroom',
  10.75,
  'bathroom',
  10.5,
  'garage',
  15.0])

# Functions

In [0]:
# methods are functions associated with object types string methods, bool methods etc...
words = ["string",'word','mot']
mot = words[2]
mots = mot.capitalize()
mots # looks like you have to assign a new variable to get string methods to work

'Mot'

In [0]:
#string methodsnot working?
Mot = mot.replace('m','n')
Mot

'not'

In [0]:
words.append('verb')
words

['string', 'word', 'mot', 'verb']

In [0]:
print(Mot.count("n"),mots.count("s"))

1 0


In [0]:
words.index('mot')

2

In [0]:
words.count('word')

1

In [0]:
words.remove('string')
words

['word', 'mot']

In [0]:
words.reverse()
words

['mot', 'word']

In [0]:
words.append("obladi")
words

['mot', 'word', 'obladi']

In [0]:
pip install numpy

In [0]:
import numpy as np
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [0]:
import math as m
r=4
area = m.pi * r**2
area

50.26548245743669

In [0]:
from math import radians
degrees = 12
r = 192500
distance = r * radians(degrees)
distance

40317.10572106901

# Numpy

In [0]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
np_baseball = np.array(baseball)
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [0]:
height = [74,74,71,72,73,75,76,74,72,72,72,71,71,76,75,73,73,74,74,72,72]
np_height = np.array(height)
np_height

array([74, 74, 71, 72, 73, 75, 76, 74, 72, 72, 72, 71, 71, 76, 75, 73, 73,
       74, 74, 72, 72])

In [0]:
np_height_meters = np_height*.0254
np_height_meters

array([1.8796, 1.8796, 1.8034, 1.8288, 1.8542, 1.905 , 1.9304, 1.8796,
       1.8288, 1.8288, 1.8288, 1.8034, 1.8034, 1.9304, 1.905 , 1.8542,
       1.8542, 1.8796, 1.8796, 1.8288, 1.8288])

In [0]:
len(height)

21

In [0]:
weight=[160,140,150,180,160,160,140,180,160,180,160,140,150,140,140,180,180,150,150,150,140]
np_weight = np.array(weight)


In [0]:
np_weight_kg=np_weight*.4536
np_weight_kg

array([72.576, 63.504, 68.04 , 81.648, 72.576, 72.576, 63.504, 81.648,
       72.576, 81.648, 72.576, 63.504, 68.04 , 63.504, 63.504, 81.648,
       81.648, 68.04 , 68.04 , 68.04 , 63.504])

In [0]:
bmi = np_weight_kg/np_height_meters**2
bmi

array([20.5429191 , 17.97505421, 20.92089088, 24.41254883, 21.10959373,
       19.99876   , 17.04144683, 23.11078399, 21.7000434 , 24.41254883,
       21.7000434 , 19.52616482, 20.92089088, 17.04144683, 17.498915  ,
       23.74829295, 23.74829295, 19.25898666, 19.25898666, 20.34379069,
       18.98753798])

In [0]:
x = [4 , 9 , 6, 3, 1]
x[1]

y = np.array(x)
y

array([4, 9, 6, 3, 1])

In [0]:
high = y > 4
y[high]


array([9, 6])

In [0]:
y[y>4]

array([9, 6])

In [0]:
y>4

array([False,  True,  True, False, False])

In [0]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [0]:
y[-3:]

array([6, 3, 1])

In [0]:
mdarray = np.zeros((3,5,2))
mdarray

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [0]:
# 2d array
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

np_baseball = np.array(baseball)
np_baseball           

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [0]:
type(np_baseball)

numpy.ndarray

In [0]:
np_baseball.shape

(4, 2)

In [0]:
# regular list of lists
x = [["a","b"], ["c","d"],["e","f"],["g","h"],["i","j"]]
x[0][1], x[1][1],x[2][1],x[3][1], x[4][1]



('b', 'd', 'f', 'h', 'j')

In [0]:
np_x = np.array(x)
np_x[:,1]

array(['b', 'd', 'f', 'h', 'j'], dtype='<U1')

In [0]:
#Basic statistics
x = [1, 4, 8, 10, 12]
np.mean(x), np.median(x)

(7.0, 8.0)

In [0]:
import random
from random import randint
u = list([randint(0,50) for x in range(7)])
u


[27, 2, 32, 46, 29, 20, 3]

In [0]:
v =[randint(0,50) for y in range(7)]
v

[27, 4, 32, 44, 32, 2, 35]

In [0]:
vmedian = np.median(v)
vmean= np.mean(v)
vstd = np.std(v)
vmedian, vmean, vstd

(32.0, 25.142857142857142, 14.797959042946925)

In [0]:
rand = [u,v]
rand

[[27, 2, 32, 46, 29, 20, 3], [27, 4, 32, 44, 32, 2, 35]]

In [0]:

nprand = np.array(rand)
nprand

array([[27,  2, 32, 46, 29, 20,  3],
       [27,  4, 32, 44, 32,  2, 35]])

In [0]:
corr = np.corrcoef(nprand[:,0], nprand[:,1])
corr

/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2534: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py:2535: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


array([[nan, nan],
       [nan,  1.]])

In [0]:
height = np.round(np.random.normal(1.75,.3,5000),2)
weight = np.round(np.random.normal(60.32,15,5000),2)
np_city = np.column_stack((height,weight))


In [0]:
np_city

array([[  1.73,  43.58],
       [  2.05,  54.35],
       [  2.15,  47.55],
       ...,
       [  1.46, 101.01],
       [  2.88,  77.84],
       [  2.01,  58.82]])

In [0]:
np.median(np_city[:,0]), np.median(np_city[:,1])

(1.75, 60.57)

In [0]:
np.mean(np_city[:,0]), np.mean(np_city[:,1])

(1.7546739999999998, 60.2532)

In [0]:
np.corrcoef(np_city[:,0], np_city[:,1])

array([[ 1.        , -0.01325805],
       [-0.01325805,  1.        ]])

In [0]:
positions = ['GK', 'M', 'A', 'D','M','M','M','D','D','D', 'A']
heights = [191, 184, 185, 180, 191, 184, 185, 180, 168, 190, 187]

In [0]:
np_heights = np.array(heights)
np_positions = np.array(positions)

In [0]:
np_heights[np_positions=='GK']

array([191])

In [0]:
np_heights[np_positions=='A'],np_heights[np_positions=='M'],np_heights[np_positions=='D']

(array([185, 187]), array([184, 191, 184, 185]), array([180, 180, 168, 190]))

In [0]:
np.median(np_heights[np_positions=='A']),np.median(np_heights[np_positions=='M']),np.median(np_heights[np_positions=='D'])

(186.0, 184.5, 180.0)